[package]
name = "rusty-haystack"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]
name = "rusty_haystack"
crate-type = ["cdylib"]

[dependencies]
haystack-core.workspace = true
haystack-client.workspace = true
haystack-server.workspace = true
pyo3 = { workspace = true, features = ["extension-module"] }
chrono.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }
