"""Type stubs for rusty_haystack — Rust-powered Project Haystack bindings."""

from datetime import datetime
from typing import Any, Iterator

# ── Exceptions ──

class HaystackError(Exception): ...
class CodecError(HaystackError): ...
class FilterError(HaystackError): ...
class GraphError(HaystackError): ...
class AuthError(HaystackError): ...
class ClientError(HaystackError): ...

# ── kinds ──

class Marker:
    """Haystack Marker tag value. Represents presence of a tag with no value."""
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class NA:
    """Haystack NA (not available) value. Indicates missing or unavailable data."""
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class Remove:
    """Haystack Remove marker. Used in diffs to indicate tag removal."""
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class Number:
    """Haystack Number with optional unit (e.g., Number(72, '°F'))."""
    val: float
    unit: str | None
    def __init__(self, val: float, unit: str | None = None) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __float__(self) -> float: ...
    def __int__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: Number) -> bool: ...
    def __le__(self, other: Number) -> bool: ...
    def __gt__(self, other: Number) -> bool: ...
    def __ge__(self, other: Number) -> bool: ...

class Ref:
    """Haystack Ref identifier with string ID and optional display name."""
    val: str
    dis: str | None
    def __init__(self, val: str, dis: str | None = None) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class Uri:
    """Haystack URI value wrapping a string URL."""
    val: str
    def __init__(self, val: str) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class Symbol:
    """Haystack Symbol value representing a def symbol reference (e.g., ^hot-water)."""
    val: str
    def __init__(self, val: str) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class XStr:
    """Haystack XStr (extended string) with type qualifier (e.g., Bin("text/plain"))."""
    type_name: str
    val: str
    def __init__(self, type_name: str, val: str) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class Coord:
    """Haystack geographic Coordinate with latitude and longitude in degrees."""
    lat: float
    lng: float
    def __init__(self, lat: float, lng: float) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class HDateTime:
    """Haystack DateTime with timezone name and UTC offset."""
    @property
    def tz_name(self) -> str:
        """The Haystack timezone name (e.g., 'New_York')."""
        ...
    def __init__(
        self,
        year: int,
        month: int,
        day: int,
        hour: int,
        minute: int,
        second: int,
        offset_seconds: int,
        tz_name: str,
    ) -> None: ...
    def dt(self) -> datetime:
        """Convert to a Python datetime.datetime object with timezone."""
        ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: HDateTime) -> bool: ...
    def __le__(self, other: HDateTime) -> bool: ...
    def __gt__(self, other: HDateTime) -> bool: ...
    def __ge__(self, other: HDateTime) -> bool: ...

# ── data ──

class HDict:
    """Haystack Dict — a collection of name/value tag pairs.

    The fundamental data type for representing entities and records.

    Examples:
        d = HDict({"dis": "Main Site", "area": Number(5000, "ft²")})
        d.get("dis")  # "Main Site"
        d.has("area")  # True
    """
    def __init__(self, tags: dict[str, Any] | None = None) -> None: ...
    def has(self, name: str) -> bool:
        """Return True if the tag is present."""
        ...
    def get(self, name: str, default: Any = None) -> Any:
        """Get a tag value by name, returning default (None) if missing."""
        ...
    def missing(self, name: str) -> bool:
        """Return True if the tag is absent."""
        ...
    def id(self) -> Ref | None:
        """Return the 'id' Ref tag value, or None."""
        ...
    def dis(self) -> str | None:
        """Return the display string ('dis' tag), or None."""
        ...
    def is_empty(self) -> bool:
        """Return True if the dict has no tags."""
        ...
    def set(self, name: str, val: Any) -> None:
        """Set a tag value. Overwrites existing."""
        ...
    def merge(self, other: HDict) -> None:
        """Merge tags from another HDict. Existing tags are overwritten."""
        ...
    @staticmethod
    def from_dict(d: dict[str, Any]) -> HDict:
        """Create an HDict from a Python dict."""
        ...
    def to_dict(self) -> dict[str, Any]:
        """Convert to a Python dict with string keys."""
        ...
    def sorted_keys(self) -> list[str]:
        """Return tag names in sorted order."""
        ...
    def copy(self) -> HDict:
        """Return a shallow copy of this dict."""
        ...
    @property
    def ref_val(self) -> str | None:
        """The ref value string of the 'id' tag, or None."""
        ...
    def tag_names(self) -> list[str]:
        """Return all tag names as a list."""
        ...
    def keys(self) -> list[str]:
        """Return tag names (alias for tag_names)."""
        ...
    def values(self) -> list[Any]:
        """Return all tag values."""
        ...
    def items(self) -> list[tuple[str, Any]]:
        """Return (name, value) pairs."""
        ...
    def __len__(self) -> int: ...
    def __contains__(self, name: str) -> bool: ...
    def __getitem__(self, name: str) -> Any: ...
    def __setitem__(self, name: str, val: Any) -> None: ...
    def __delitem__(self, name: str) -> None: ...
    def __iter__(self) -> Iterator[str]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class HCol:
    """Haystack Column definition with name and optional metadata."""
    name: str
    def __init__(self, name: str, meta: HDict | None = None) -> None: ...
    @property
    def meta(self) -> HDict:
        """Column metadata as an HDict."""
        ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class HGrid:
    """Haystack Grid — a two-dimensional table of tagged data.

    The primary data exchange format in the Haystack protocol.

    Examples:
        g = HGrid()
        g = HGrid.from_parts(meta, cols, rows)
        g.add_row(HDict({"dis": "Room 101"}))
    """
    def __init__(self) -> None: ...
    @staticmethod
    def from_parts(meta: HDict, cols: list[HCol], rows: list[HDict]) -> HGrid:
        """Construct a grid from metadata, columns, and rows."""
        ...
    def add_row(self, row: HDict) -> None:
        """Add a row (HDict) to the grid."""
        ...
    def set_meta(self, meta: HDict) -> None:
        """Set the grid metadata."""
        ...
    def add_col(self, name: str, meta: HDict | None = None) -> None:
        """Add a column to the grid."""
        ...
    def rows(self) -> list[HDict]:
        """Return all rows as a list of HDict."""
        ...
    def cols(self) -> list[HCol]:
        """Return all columns as a list of HCol."""
        ...
    def col(self, name: str) -> HCol | None:
        """Look up a column by name."""
        ...
    def col_names(self) -> list[str]:
        """Return column names as a list."""
        ...
    def num_cols(self) -> int:
        """Return the number of columns."""
        ...
    def meta(self) -> HDict:
        """Return the grid metadata."""
        ...
    def is_empty(self) -> bool:
        """Return True if the grid has no rows."""
        ...
    def is_err(self) -> bool:
        """Return True if this is an error grid."""
        ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> HDict: ...
    def __iter__(self) -> Iterator[HDict]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class HList:
    """Haystack List — an ordered collection of Haystack values."""
    def __init__(self, items: list[Any] | None = None) -> None: ...
    def push(self, val: Any) -> None:
        """Append a single value to the list."""
        ...
    def extend(self, other: HList) -> None:
        """Extend this list with items from another HList."""
        ...
    def clear(self) -> None:
        """Remove all items from the list."""
        ...
    def is_empty(self) -> bool:
        """Return True if the list is empty."""
        ...
    @property
    def len(self) -> int:
        """Number of items in the list."""
        ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Any: ...
    def __setitem__(self, index: int, val: Any) -> None: ...
    def __delitem__(self, index: int) -> None: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

# ── codecs ──

def encode_grid(codec_name: str, grid: HGrid) -> str:
    """Encode an HGrid to a string using the specified codec.

    Supported codecs: 'text/zinc', 'application/json', 'application/json;v=3',
    'text/trio', 'text/csv'.
    """
    ...

def decode_grid(codec_name: str, data: str) -> HGrid:
    """Decode a string to an HGrid using the specified codec."""
    ...

def encode_scalar(codec_name: str, val: Any) -> str:
    """Encode a scalar Haystack value to a string."""
    ...

def decode_scalar(codec_name: str, data: str) -> Any:
    """Decode a string to a scalar Haystack value."""
    ...

# ── filter ──

class CmpOp:
    """Comparison operator for filter expressions."""
    Eq: CmpOp
    Ne: CmpOp
    Lt: CmpOp
    Le: CmpOp
    Gt: CmpOp
    Ge: CmpOp
    def __repr__(self) -> str: ...

class Path:
    """Haystack filter path for tag traversal (e.g., 'equipRef->siteRef->area')."""
    def __init__(self, segments: list[str]) -> None: ...
    @staticmethod
    def single(name: str) -> Path:
        """Create a single-segment path."""
        ...
    @property
    def segments(self) -> list[str]:
        """Path segments."""
        ...
    def is_single(self) -> bool:
        """True if this path has only one segment."""
        ...
    def first(self) -> str:
        """First segment name."""
        ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __len__(self) -> int: ...

class Filter:
    """Haystack filter expression with builder pattern and AST inspection.

    Filters can be constructed by parsing or using the builder API.
    Supports Python & (and) and | (or) operators.

    Examples:
        f = Filter.parse("site and area > 1000")
        f = Filter.has("site") & Filter.eq("area", Number(1000))
        f.matches(entity)
    """
    @staticmethod
    def parse(expr: str) -> Filter:
        """Parse a Haystack filter expression string."""
        ...
    @staticmethod
    def has(tag: str) -> Filter:
        """Create a 'has' filter: tag is present."""
        ...
    @staticmethod
    def missing(tag: str) -> Filter:
        """Create a 'missing' filter: tag is absent."""
        ...
    @staticmethod
    def cmp(path: Path, op: CmpOp, val: Any) -> Filter:
        """Create a comparison filter with a Path, operator, and value."""
        ...
    @staticmethod
    def eq(tag: str, val: Any) -> Filter:
        """Create an equals comparison: tag == val."""
        ...
    def and_(self, other: Filter) -> Filter:
        """Combine with AND."""
        ...
    def or_(self, other: Filter) -> Filter:
        """Combine with OR."""
        ...
    def matches(self, entity: HDict) -> bool:
        """Evaluate this filter against an entity dict."""
        ...
    @property
    def node_type(self) -> str:
        """Node type: 'has', 'missing', 'cmp', 'and', 'or', 'specMatch'."""
        ...
    @property
    def path(self) -> Path | None:
        """For Has/Missing/Cmp nodes, the tag path. None for And/Or."""
        ...
    @property
    def op(self) -> CmpOp | None:
        """For Cmp nodes, the comparison operator. None for others."""
        ...
    def val(self) -> Any | None:
        """For Cmp nodes, the comparison value. None for others."""
        ...
    def children(self) -> tuple[Filter, Filter] | None:
        """For And/Or nodes, return (left, right). None for others."""
        ...
    def __and__(self, other: Filter) -> Filter: ...
    def __or__(self, other: Filter) -> Filter: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

def parse_filter(expr: str) -> str:
    """Parse a filter expression and return its AST as a debug string."""
    ...

def matches_filter(filter_expr: str, entity: HDict) -> bool:
    """Evaluate a filter expression against an entity dict."""
    ...

# ── graph ──

class DiffOp:
    """Type of graph change: Add, Update, or Remove."""
    Add: DiffOp
    Update: DiffOp
    Remove: DiffOp
    def __repr__(self) -> str: ...

class GraphDiff:
    """Record of a single change to the entity graph."""
    version: int
    timestamp: int
    op: DiffOp
    ref_val: str
    @property
    def old(self) -> HDict | None:
        """Entity state before the mutation (None for Add)."""
        ...
    @property
    def new(self) -> HDict | None:
        """Entity state after the mutation (None for Remove)."""
        ...
    @property
    def changed_tags(self) -> HDict | None:
        """For Update: tags that changed with their new values."""
        ...
    @property
    def previous_tags(self) -> HDict | None:
        """For Update: tags that changed with their previous values."""
        ...
    def __repr__(self) -> str: ...

class EntityGraph:
    """In-memory entity graph with bitmap tag indexing, filter queries, and change tracking.

    Examples:
        g = EntityGraph()
        g.add(HDict({"id": Ref("site-1"), "site": Marker(), "dis": "HQ"}))
        results = g.read("site")
    """
    def __init__(self) -> None: ...
    @staticmethod
    def with_namespace(ns: DefNamespace) -> EntityGraph:
        """Create a graph with an attached ontology namespace for validation.

        Warning: consumes the namespace — the original object becomes empty.
        """
        ...
    @staticmethod
    def from_grid(grid: HGrid, ns: DefNamespace | None = None) -> EntityGraph:
        """Bulk-load entities from an HGrid. Each row must have an 'id' Ref tag.

        Warning: if ns is provided, it is consumed.
        """
        ...
    def add(self, entity: HDict) -> str:
        """Add an entity (must have an 'id' Ref tag). Returns the ref value string."""
        ...
    def add_grid(self, grid: HGrid) -> int:
        """Add multiple entities from an HGrid. Returns number added."""
        ...
    def get(self, ref_val: str) -> HDict | None:
        """Get an entity by ref value. Returns HDict or None."""
        ...
    def update(self, ref_val: str, changes: HDict) -> None:
        """Update an entity by merging changes into existing tags."""
        ...
    def remove(self, ref_val: str) -> HDict:
        """Remove an entity by ref value. Returns the removed HDict."""
        ...
    def read(self, filter_expr: str, limit: int = 0) -> HGrid:
        """Run a filter expression and return matching entities as a grid.

        Args:
            filter_expr: Haystack filter string (e.g., 'site', 'temp > 72').
            limit: Max results (0 for unlimited).
        """
        ...
    def all(self) -> list[HDict]:
        """Return all entities as a list of HDict."""
        ...
    def is_empty(self) -> bool:
        """Return True if the graph has no entities."""
        ...
    def validate(self) -> list[str]:
        """Validate all entities against the attached namespace."""
        ...
    def changes_since(self, version: int) -> list[GraphDiff]:
        """Return changelog entries since a given graph version.

        Raises RuntimeError if the subscriber has fallen behind (changelog gap).
        """
        ...
    def index_field(self, field: str) -> None:
        """Enable a B-tree value index on a tag for faster range queries."""
        ...
    def refs_from(self, ref_val: str, ref_type: str | None = None) -> list[str]:
        """Get ref values that the given entity points to."""
        ...
    def refs_to(self, ref_val: str, ref_type: str | None = None) -> list[str]:
        """Get ref values of entities pointing to the given entity."""
        ...
    def to_grid(self, filter_expr: str = "") -> HGrid:
        """Export matching entities to a grid. Empty filter exports all."""
        ...
    def ref_chain(self, ref_val: str, ref_tags: list[str]) -> list[HDict]:
        """Walk the ref chain from an entity following the given ref tags in order.

        Returns a list of HDict entities along the chain.
        """
        ...
    def site_for(self, ref_val: str) -> HDict | None:
        """Find the site entity for any entity by walking up the ref chain."""
        ...
    def children_of(self, ref_val: str) -> list[HDict]:
        """Get all direct children of an entity (entities whose xxxRef points to it)."""
        ...
    def equip_points(
        self, equip_ref: str, filter: str | None = None
    ) -> list[HDict]:
        """Get all points for an equip, optionally filtered.

        Raises GraphError on invalid filter expression.
        """
        ...
    def hierarchy_tree(
        self, root: str, max_depth: int = 10
    ) -> dict[str, Any] | None:
        """Build a hierarchy tree from a root entity.

        Returns a nested dict: {"entity": HDict, "depth": int, "children": [...]},
        or None if the root is not found.
        """
        ...
    def classify(self, ref_val: str) -> str | None:
        """Classify an entity by its most specific type tag."""
        ...
    @property
    def version(self) -> int:
        """Current graph version (increments on every mutation)."""
        ...
    def __len__(self) -> int: ...
    def __contains__(self, ref_val: str) -> bool: ...
    def __repr__(self) -> str: ...

class SharedGraph:
    """Thread-safe shared entity graph backed by Arc<RwLock<EntityGraph>>.

    Safe for concurrent reads and serialized writes.
    """
    def __init__(self, graph: EntityGraph | None = None) -> None: ...
    @staticmethod
    def from_grid(grid: HGrid, ns: DefNamespace | None = None) -> SharedGraph:
        """Create a SharedGraph from an HGrid."""
        ...
    def add(self, entity: HDict) -> str:
        """Add an entity. Returns the ref value string."""
        ...
    def get(self, ref_val: str) -> HDict | None:
        """Get an entity by ref value. Returns HDict or None."""
        ...
    def update(self, ref_val: str, changes: HDict) -> None:
        """Update an entity by merging changes."""
        ...
    def remove(self, ref_val: str) -> HDict:
        """Remove an entity. Returns the removed HDict."""
        ...
    def read(self, filter_expr: str, limit: int = 0) -> HGrid:
        """Query entities matching a Haystack filter."""
        ...
    def all(self) -> list[HDict]:
        """Return all entities as a list of HDict."""
        ...
    def is_empty(self) -> bool:
        """Return True if the graph has no entities."""
        ...
    def contains(self, ref_val: str) -> bool:
        """Return True if an entity with the given ref exists."""
        ...
    def refs_from(self, ref_val: str, ref_type: str | None = None) -> list[str]:
        """Get ref values that the given entity points to."""
        ...
    def refs_to(self, ref_val: str, ref_type: str | None = None) -> list[str]:
        """Get ref values of entities pointing to the given entity."""
        ...
    def changes_since(self, version: int) -> list[GraphDiff]:
        """Return changelog entries since a given graph version.

        Raises RuntimeError if the subscriber has fallen behind (changelog gap).
        """
        ...
    def validate(self) -> list[str]:
        """Validate all entities against the attached namespace."""
        ...
    @property
    def subscriber_count(self) -> int:
        """Number of active broadcast subscribers."""
        ...
    def ref_chain(self, ref_val: str, ref_tags: list[str]) -> list[HDict]:
        """Walk the ref chain from an entity following the given ref tags in order."""
        ...
    def site_for(self, ref_val: str) -> HDict | None:
        """Find the site entity for any entity by walking up the ref chain."""
        ...
    def children_of(self, ref_val: str) -> list[HDict]:
        """Get all direct children of an entity."""
        ...
    def equip_points(
        self, equip_ref: str, filter: str | None = None
    ) -> list[HDict]:
        """Get all points for an equip, optionally filtered.

        Raises GraphError on invalid filter expression.
        """
        ...
    def hierarchy_tree(
        self, root: str, max_depth: int = 10
    ) -> dict[str, Any] | None:
        """Build a hierarchy tree from a root entity.

        Returns a nested dict or None if the root is not found.
        """
        ...
    def classify(self, ref_val: str) -> str | None:
        """Classify an entity by its most specific type tag."""
        ...
    @property
    def version(self) -> int:
        """Current graph version."""
        ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

# ── ontology ──

class DefKind:
    """Classification of a Haystack definition."""
    Marker: DefKind
    Val: DefKind
    Entity: DefKind
    Feature: DefKind
    Conjunct: DefKind
    Choice: DefKind
    Lib: DefKind
    def __repr__(self) -> str: ...

class Slot:
    """A resolved Xeto slot."""
    @property
    def name(self) -> str: ...
    @property
    def qname(self) -> str: ...
    @property
    def type_name(self) -> str: ...
    @property
    def doc(self) -> str: ...
    @property
    def val(self) -> str | None: ...
    def __repr__(self) -> str: ...

class Spec:
    """A resolved Xeto spec."""
    @property
    def qname(self) -> str: ...
    @property
    def type_name(self) -> str: ...
    @property
    def base(self) -> str | None: ...
    @property
    def doc(self) -> str: ...
    @property
    def is_abstract(self) -> bool: ...
    @property
    def is_sealed(self) -> bool: ...
    def slots(self) -> list[Slot]: ...
    def __repr__(self) -> str: ...

class Def:
    """A Haystack definition record (tag, entity type, conjunct, etc.)."""
    @property
    def symbol(self) -> str: ...
    @property
    def lib(self) -> str: ...
    def supertypes(self) -> list[str]: ...
    @property
    def kind(self) -> DefKind | None: ...
    @property
    def doc(self) -> str: ...
    def tag_on(self) -> list[str]: ...
    def tags(self) -> HDict: ...
    def __repr__(self) -> str: ...

class Lib:
    """A Haystack library containing definitions."""
    @property
    def name(self) -> str: ...
    @property
    def version(self) -> str: ...
    @property
    def doc(self) -> str: ...
    @property
    def depends(self) -> list[str]: ...
    def defs(self) -> list[Def]: ...
    def get_def(self, symbol: str) -> Def | None: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class DefNamespace:
    """Haystack definition namespace with taxonomy, validation, and spec resolution."""
    def __init__(self) -> None: ...
    def load_lib(self, name: str) -> None: ...
    def load_trio_str(self, trio: str, lib_name: str) -> None: ...
    def fits(self, sub: str, super_: str) -> bool: ...
    def fits_explain(self, sub: str, super_: str) -> str: ...
    def get_def(self, symbol: str) -> Def | None: ...
    def mandatory_tags(self, symbol: str) -> list[str]: ...
    def tags_for(self, symbol: str) -> HDict: ...
    def choices(self, symbol: str) -> list[str]: ...
    def defs(self) -> list[Def]: ...
    def libs(self) -> list[Lib]: ...
    def get_lib(self, name: str) -> Lib | None: ...
    def __repr__(self) -> str: ...

# ── auth ──

def derive_credentials(
    password: str, salt: bytes, iterations: int
) -> tuple[bytes, bytes]:
    """Derive SCRAM SHA-256 credentials. Returns (stored_key, server_key)."""
    ...

def generate_nonce(length: int = 24) -> str:
    """Generate a random base64-encoded nonce string."""
    ...

def client_first_message(username: str, nonce: str) -> str:
    """Create the SCRAM client-first-message."""
    ...

def client_final_message(
    server_first: str, client_first_bare: str, password: str
) -> str:
    """Create the SCRAM client-final-message."""
    ...

def extract_client_nonce(client_first: str) -> str | None:
    """Extract the nonce from a client-first-message."""
    ...

def parse_auth_header(header: str) -> dict[str, str]:
    """Parse a WWW-Authenticate or Authorization header into key-value pairs."""
    ...

def format_www_authenticate(
    nonce: str, salt: str, iterations: int, hash_func: str
) -> str:
    """Format a WWW-Authenticate SCRAM challenge header."""
    ...

def format_auth_info(server_signature: str) -> str:
    """Format an Authentication-Info header with server signature."""
    ...

# ── client ──

class TlsConfig:
    """TLS client configuration for mTLS connections."""
    @staticmethod
    def from_files(
        cert_path: str, key_path: str, ca_path: str | None = None
    ) -> TlsConfig:
        """Load TLS certificates from file paths."""
        ...
    def __repr__(self) -> str: ...

class HaystackClient:
    """Haystack HTTP client with SCRAM SHA-256 authentication.

    All methods are synchronous (blocking). The GIL is released during
    network I/O so other Python threads can run.

    Examples:
        client = HaystackClient.connect("http://localhost:8080", "admin", "pass")
        sites = client.read("site")
        client.close()
    """
    @staticmethod
    def connect(url: str, username: str, password: str) -> HaystackClient:
        """Connect to a Haystack server over HTTP with SCRAM auth."""
        ...
    @staticmethod
    def connect_tls(
        url: str,
        username: str,
        password: str,
        tls: TlsConfig,
    ) -> HaystackClient:
        """Connect with mutual TLS authentication."""
        ...
    def about(self) -> HGrid:
        """Query the server's about information."""
        ...
    def ops(self) -> HGrid:
        """Query supported operations."""
        ...
    def formats(self) -> HGrid:
        """Query supported wire formats."""
        ...
    def libs(self) -> HGrid:
        """Query loaded ontology libraries."""
        ...
    def read(self, filter: str, limit: int | None = None) -> HGrid:
        """Read entities matching a Haystack filter expression.

        Args:
            filter: Haystack filter (e.g., 'site', 'equip and siteRef==@s').
            limit: Maximum results (None for unlimited).
        """
        ...
    def read_by_ids(self, ids: list[str]) -> HGrid:
        """Read entities by their ref ID strings."""
        ...
    def nav(self, nav_id: str | None = None) -> HGrid:
        """Navigate the entity tree. None for root."""
        ...
    def defs(self, filter: str | None = None) -> HGrid:
        """Query ontology definitions with optional filter."""
        ...
    def watch_sub(self, ids: list[str], lease: str | None = None) -> HGrid:
        """Subscribe to entity watches. Lease: '1min', '1hr', etc."""
        ...
    def watch_poll(self, watch_id: str) -> HGrid:
        """Poll a watch for changed entities."""
        ...
    def watch_unsub(self, watch_id: str, ids: list[str] | None = None) -> HGrid:
        """Unsubscribe from a watch. ids=None closes entire watch."""
        ...
    def point_write(self, id: str, level: int, val: Any) -> HGrid:
        """Write a value to a writable point at a priority level (1-17)."""
        ...
    def his_read(self, id: str, range: str) -> HGrid:
        """Read historical data. Range: 'today', '2024-01-01,2024-01-31', etc."""
        ...
    def his_write(self, id: str, items: list[HDict]) -> HGrid:
        """Write historical data. Items are HDict rows with 'ts' and 'val' tags."""
        ...
    def invoke_action(self, id: str, action: str, args: HDict | None = None) -> HGrid:
        """Invoke a named action on an entity."""
        ...
    def specs(self, lib: str | None = None) -> HGrid:
        """Query ontology specs, optionally filtered by library."""
        ...
    def spec(self, qname: str) -> HGrid:
        """Get a single spec by qualified name."""
        ...
    def load_lib(self, name: str, source: str) -> HGrid:
        """Load an ontology library from Trio source."""
        ...
    def unload_lib(self, name: str) -> HGrid:
        """Unload an ontology library by name."""
        ...
    def export_lib(self, name: str) -> HGrid:
        """Export an ontology library as Trio source."""
        ...
    def validate(self, entities: list[HDict]) -> HGrid:
        """Validate entities against the server's ontology."""
        ...
    def call(self, op: str, req: HGrid) -> HGrid:
        """Send a raw op request. Returns the response grid."""
        ...
    def close(self) -> None:
        """Close the client connection."""
        ...
    def __repr__(self) -> str: ...

class WsClient:
    """Haystack WebSocket client with SCRAM authentication.

    Connects via HTTP for auth, then upgrades to WebSocket for operations.
    Ideal for long-lived connections and watch subscriptions.
    """
    @staticmethod
    def connect(
        url: str, ws_url: str, username: str, password: str
    ) -> WsClient:
        """Connect via HTTP for auth, then upgrade to WebSocket."""
        ...
    def about(self) -> HGrid:
        """Query server about information over WebSocket."""
        ...
    def ops(self) -> HGrid:
        """Query supported operations over WebSocket."""
        ...
    def read(self, filter: str, limit: int | None = None) -> HGrid:
        """Read entities matching a filter over WebSocket."""
        ...
    def read_by_ids(self, ids: list[str]) -> HGrid:
        """Read entities by ID over WebSocket."""
        ...
    def nav(self, nav_id: str | None = None) -> HGrid:
        """Navigate entity tree over WebSocket."""
        ...
    def watch_sub(self, ids: list[str], lease: str | None = None) -> HGrid:
        """Subscribe to entity watches over WebSocket."""
        ...
    def watch_poll(self, watch_id: str) -> HGrid:
        """Poll a watch over WebSocket."""
        ...
    def his_read(self, id: str, range: str) -> HGrid:
        """Read historical data over WebSocket."""
        ...
    def point_write(self, id: str, level: int, val: Any) -> HGrid:
        """Write to a writable point over WebSocket."""
        ...
    def call(self, op: str, req: HGrid) -> HGrid:
        """Send a raw op request over WebSocket."""
        ...
    def close(self) -> None:
        """Close the WebSocket connection."""
        ...
    def __repr__(self) -> str: ...

# ── server ──

class AuthManager:
    """SCRAM SHA-256 authentication manager for the server."""
    @staticmethod
    def empty() -> AuthManager:
        """Create a disabled (no-auth) manager."""
        ...
    @staticmethod
    def from_toml(path: str) -> AuthManager:
        """Load auth configuration from a TOML file path."""
        ...
    @staticmethod
    def from_toml_str(content: str) -> AuthManager:
        """Load auth configuration from a TOML string."""
        ...
    def is_enabled(self) -> bool:
        """Whether authentication is enabled (has users configured)."""
        ...
    def __repr__(self) -> str: ...

class HisStore:
    """In-memory history storage for time-series point data."""
    def __init__(self) -> None: ...
    def len(self, id: str) -> int:
        """Number of history records for a given entity ID."""
        ...
    def __repr__(self) -> str: ...

class HaystackServer:
    """Embedded Haystack HTTP API server with builder-pattern configuration.

    Note: with_namespace/with_auth consume their argument
    (the original Python object becomes empty after the call).

    Examples:
        server = HaystackServer(SharedGraph())
        server.with_auth(auth)
        server.port(8080)
        server.run()  # blocks
    """
    def __init__(self, graph: SharedGraph) -> None: ...
    def with_namespace(self, ns: DefNamespace) -> None:
        """Set the ontology namespace. Warning: consumes the namespace."""
        ...
    def with_auth(self, auth: AuthManager) -> None:
        """Set the auth manager. Warning: consumes the auth manager."""
        ...
    def port(self, port: int) -> None:
        """Set the HTTP listen port (default 8080)."""
        ...
    def host(self, host: str) -> None:
        """Set the HTTP listen host (default '0.0.0.0')."""
        ...
    def run(self) -> None:
        """Start the server, blocking the calling thread. Releases the GIL."""
        ...
    def run_background(self) -> None:
        """Start the server in a background thread. Returns immediately."""
        ...
    def bg_error(self) -> str | None:
        """Retrieve the background server error message, if any."""
        ...
    def __repr__(self) -> str: ...

# ── Submodule re-exports ──
# All types are also available under submodules:
#   rusty_haystack.kinds.Marker, .Number, .Ref, .Uri, .Symbol, .XStr, .Coord, .HDateTime
#   rusty_haystack.data.HDict, .HGrid, .HCol, .HList
#   rusty_haystack.codecs.encode_grid, .decode_grid, .encode_scalar, .decode_scalar
#   rusty_haystack.filter.Filter, .CmpOp, .Path, .parse_filter, .matches_filter
#   rusty_haystack.graph.EntityGraph, .SharedGraph, .GraphDiff, .DiffOp
#   rusty_haystack.ontology.DefNamespace, .Def, .Lib, .DefKind, .Spec, .Slot
#   rusty_haystack.auth.derive_credentials, .generate_nonce, etc.
#   rusty_haystack.client.HaystackClient, .WsClient, .TlsConfig
#   rusty_haystack.server.HaystackServer, .AuthManager, .HisStore
